# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionNew_Combo = QtGui.QAction(parent=MainWindow)
        self.actionNew_Combo.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionNew_Combo.setObjectName("actionNew_Combo")
        self.actionDisplay_Menu = QtGui.QAction(parent=MainWindow)
        self.actionDisplay_Menu.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionDisplay_Menu.setObjectName("actionDisplay_Menu")
        self.actionSearch_Combos = QtGui.QAction(parent=MainWindow)
        self.actionSearch_Combos.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionSearch_Combos.setObjectName("actionSearch_Combos")
        self.toolBar.addAction(self.actionNew_Combo)
        self.toolBar.addAction(self.actionDisplay_Menu)
        self.toolBar.addAction(self.actionSearch_Combos)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew_Combo.setText(_translate("MainWindow", "New Combo"))
        self.actionNew_Combo.setToolTip(_translate("MainWindow", "Create a new combo"))
        self.actionDisplay_Menu.setText(_translate("MainWindow", "Display Menu"))
        self.actionDisplay_Menu.setToolTip(_translate("MainWindow", "Display the full menu"))
        self.actionSearch_Combos.setText(_translate("MainWindow", "Search Combos"))
        self.actionSearch_Combos.setToolTip(_translate("MainWindow", "Search for a specific combo from the menu"))
